controller_manager:
  ros__parameters:
    update_rate: 100.0

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100.0

J1_position_controller:
  ros__parameters:
    type: position_controllers/PositionController
    joint: J1
    pid: {p: 100.0, i: 0.01, d: 10.0}

J2_position_controller:
  ros__parameters:
    type: position_controllers/PositionController
    joint: J2
    pid: {p: 100.0, i: 0.01, d: 10.0}

J3_position_controller:
  ros__parameters:
    type: position_controllers/PositionController
    joint: J3
    pid: {p: 100.0, i: 0.01, d: 10.0}
